Repository DeFiCh/defichain-app, pull requests merged in 2021-06, with the labels that each got.

#902 caching issues, mn issues, improvements on usability, translations
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  package-lock.json
  package.json
  typings/walletMap.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/components/LiquidityAccordion/index.tsx
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/LiquidityPage/components/AvailablePoolPairsList/index.tsx
  webapp/src/containers/LiquidityPage/components/LiquidityInfo/index.tsx
  webapp/src/containers/LiquidityPage/service.tsx
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/MasternodesPage/service.tsx
  webapp/src/containers/PopOver/SnapshotDownloadModal/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabGeneral/index.tsx
  webapp/src/containers/SettingsPage/service.tsx
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/Sidebar/index.tsx
  webapp/src/containers/SyncStatus/SnapshotIcon/index.tsx
  webapp/src/containers/WalletPage/components/Balances/BalancesTokenCard/index.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
  webapp/src/utils/rpc-client.ts
  webapp/src/utils/utility.ts
Labels: kind/fix

#914 feat: bump node to 1.7.5 and MN updates
  electron-app/assets/icon/linux/512x512.png
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/feature

#916 bump node to 1.7.6
  package.json
  webapp/src/containers/MasternodesPage/masterNodeInterface.ts
  webapp/src/containers/MasternodesPage/saga.tsx
Labels: kind/chore

#920 bump npm dependencies
  .github/CODEOWNERS
  .github/workflows/dev-builds.yml
  .github/workflows/release-builds.yml
  .nvmrc
  electron-app/src/controllers/wallets.ts
  electron-app/src/ipc-events/appUpdateManager.ts
  electron-app/src/services/defiprocessmanager.ts
  package-lock.json
  package.json
  tslint.json
  webapp/package-lock.json
  webapp/package.json
Labels: kind/chore

#923 Bump ain to v1.7.7
  package.json
Labels: kind/chore

#924 bump app version to v2.4.5
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/chore

#927 updated deps, remove unused components
  electron-app/src/constants/dirpath.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/MasternodesPage/__test__/mapChart.test.tsx
  webapp/src/containers/MasternodesPage/components/MapChart/index.tsx
  webapp/src/containers/MasternodesPage/components/Statistics/index.tsx
  webapp/src/containers/SwapPage/index.tsx
Labels: kind/chore

#928 download snapshot from menu
  electron-app/src/controllers/snapshot.ts
  electron-app/src/menus/index.ts
Labels: kind/feature

#944 make stats api as fallback
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/LiquidityPage/service.tsx
  webapp/src/utils/stats.ts
  webapp/src/utils/utility.ts
Labels: kind/feature

#946 notarized mac app
  .github/workflows/dev-builds.yml
  .github/workflows/release-builds.yml
  .github/workflows/sync-labels.yml
  electron-app/assets/entitlements.mac.plist
  package.json
Labels: kind/feature

#959 bump app and node version to 1.7.10
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/feature

#981 Update 1-bug-report.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
Labels: kind/docs
