Repository DeFiCh/defichain-app, pull requests merged in 2021-04, with the labels that each got.

#685 Fix/security settings
  webapp/src/components/walletDropdown/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/index.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/translations/languages/en.json
Labels: kind/feature

#713 feat: snapshot download
  electron-app/src/app.ts
  electron-app/src/constants/dirpath.ts
  electron-app/src/controllers/snapshot.ts
  electron-app/src/ipc-events/defiprocessmanager.ts
  electron-app/src/services/defiprocessmanager.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  typings/ipcEvents.ts
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/App.tsx
  webapp/src/app/service.tsx
  webapp/src/app/snapshot.ipcRenderer.ts
  webapp/src/app/startupSaga.ts
  webapp/src/constants/configs.ts
  webapp/src/containers/PopOver/GeneralReIndexModal/index.tsx
  webapp/src/containers/PopOver/ReIndexModel/index.tsx
  webapp/src/containers/PopOver/SnapshotDownloadModal/index.tsx
  webapp/src/containers/PopOver/__test__/GeneralReIndexModal.test.tsx
  webapp/src/containers/PopOver/__test__/__snapshots__/GeneralReIndexModal.test.tsx.snap
  webapp/src/containers/PopOver/popOver.module.scss
  webapp/src/containers/PopOver/reducer.ts
  webapp/src/containers/PopOver/service.tsx
  webapp/src/containers/PopOver/types.ts
  webapp/src/containers/SettingsPage/__test__/SettingsTabGeneral.test.tsx
  webapp/src/containers/SettingsPage/__test__/__snapshots__/SettingsTabGeneral.test.tsx.snap
  webapp/src/containers/SettingsPage/components/SettingsTabGeneral/index.tsx
  webapp/src/containers/SyncStatus/SnapshotIcon/index.tsx
  webapp/src/containers/SyncStatus/SyncStatus.module.scss
  webapp/src/containers/SyncStatus/index.tsx
  webapp/src/containers/SyncStatus/service.tsx
  webapp/src/scss/bootstrap/_progress.scss
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/utils/isElectron.ts
Labels: kind/feature

#714 feature: bump app to v2.3.3 and node to v1.6.1
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/feature

#718 chore: updated block to 746484
  typings/snapshot.ts
Labels: kind/feature

#705 Fix/masternode UI
  webapp/src/constants/configs.ts
  webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx
  webapp/src/containers/MasternodesPage/index.tsx
Labels: kind/fix

#719 chore: bump to rc 1
  package.json
  webapp/package.json
Labels: kind/chore

#720 moved codeowners to individuals
  .github/CODEOWNERS
Labels: kind/chore

#689 fix : Exceed limit in csv
  webapp/src/constants/configs.ts
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Labels: kind/fix

#725 Revert "Fix/Send page max amount logic"
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
Labels: kind/chore

#724 feat: add error block if space is not enough
  electron-app/src/constants/dirpath.ts
  electron-app/src/controllers/snapshot.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  typings/ipcEvents.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/snapshot.ipcRenderer.ts
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/feature

#726 chore: bump to node 1.6.2
  package.json
Labels: kind/feature

#727 feat: reindex wallet via menu bar
  electron-app/src/menus/index.ts
  typings/ipcEvents.ts
  webapp/src/app/menu.ipcRenderer.ts
  webapp/src/containers/SettingsPage/reducer.ts
  webapp/src/containers/SettingsPage/saga.tsx
Labels: kind/feature

#728 feat: added log and removed multiplier
  electron-app/src/controllers/snapshot.ts
Labels: kind/feature

#729 fix: remove available space validation
  electron-app/src/controllers/snapshot.ts
Labels: kind/fix

#730 feat: label updates
  electron-app/src/menus/index.ts
  webapp/src/translations/languages/de.json
Labels: kind/fix

#732 feat: update to Electron 12
  .nvmrc
  electron-app/src/app.ts
  electron-app/src/services/uiconfig.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/SettingsPage/components/SettingsChangePassphrase/index.tsx
  webapp/src/containers/WalletPage/components/EncryptWalletPage/index.tsx
  webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx
  webapp/src/utils/electronLogger.ts
Labels: kind/feature

#752 feat: snapshot region selector
  electron-app/src/controllers/snapshot.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  typings/fileExtensions.ts
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/service.tsx
  webapp/src/containers/PopOver/ReIndexModel/index.tsx
  webapp/src/containers/PopOver/SnapshotDownloadModal/index.tsx
  webapp/src/containers/PopOver/reducer.ts
  webapp/src/containers/PopOver/service.tsx
  webapp/src/translations/languages/en.json
Labels: kind/feature

#767 Secure rpcallowip default
  typings/settings.ts
Labels: kind/fix

#773 Add more wallet timeout options and refactor
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/types.ts
Labels: kind/refactor

#771 Use Auth header for RPC calls instead of clear text urls
  webapp/src/utils/rpc-client.ts
Labels: kind/fix

#783 fix: remove deprecated method and white screen issue
  electron-app/src/constants/dirpath.ts
  webapp/src/utils/electronLogger.ts
Labels: kind/fix

#786 chore: bump packages
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
Labels: kind/chore

#791 fix: move mac defi.conf to default folder
  electron-app/src/constants/dirpath.ts
  electron-app/src/services/uiconfig.ts
  electron-app/src/utils.ts
Labels: kind/fix

#793 fix: duplicate path
  electron-app/src/constants/dirpath.ts
Labels: kind/fix
