Repository DeFiCh/defichain-app, pull requests merged in 2021-02, with the labels that each got.

#526 Release drafting automation
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: kind/chore

#524 Run dev-builds only on PR to reduce concurrency cap
  .github/workflows/dev-builds.yml
Labels: kind/chore

#523 Fix codeowners misconfiguration
  .github/CODEOWNERS
Labels: kind/chore

#528 Fix/csv export transactions feature
  webapp/src/containers/WalletPage/components/WalletTxnsNew/components/DownloadCsvModal/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Labels: kind/fix

#522 feat: passphrase strength meter
  .husky/.gitignore
  package-lock.json
  package.json
  webapp/.eslintrc.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/InputPassword/InputPassword.module.scss
  webapp/src/components/InputPassword/index.tsx
  webapp/src/containers/PopOver/EncryptWalletModal/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsChangePassphrase/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx
  webapp/src/containers/SettingsPage/index.tsx
  webapp/src/containers/WalletPage/components/CreateWallet/index.tsx
  webapp/src/containers/WalletPage/components/EncryptWalletPage/index.tsx
  webapp/src/translations/languages/en.json
  webapp/src/utils/passwordUtility.ts
Labels: kind/feature

#531 feature: force reindex on node update
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  electron-app/src/utils.ts
  package.json
  tsconfig.json
  typings/ipcEvents.ts
  typings/settings.ts
  typings/walletMap.ts
  webapp/src/app/service.tsx
  webapp/src/containers/PopOver/ReIndexModel/index.tsx
  webapp/src/containers/PopOver/__test__/reducer.test.tsx
  webapp/src/containers/PopOver/reducer.tsx
  webapp/src/containers/WalletPage/saga.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/feature

#530 Automated issue governance
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/governance.yml
  .github/labels.yml
Labels: kind/chore

#533 build: update release type to draft
  package.json
Labels: kind/chore

#534 Revert "build: update release type to draft"
  package.json
Labels: kind/chore

#537 fix: german translation for block transaction failed
  webapp/src/translations/languages/de.json
Labels: kind/fix

#539 chore, docs, refactor excluded from release
  .github/release-drafter.yml
Labels: kind/chore

#538 fix: remap mempool err to blocks pending
  webapp/src/constants/common.ts
Labels: kind/fix

#547 fix: set node version with state
  webapp/src/app/service.tsx
  webapp/src/containers/PopOver/ReIndexModel/index.tsx
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/saga.ts
Labels: kind/fix

#548 fix: temporary disable masternodes creation
  webapp/src/containers/MasternodesPage/index.tsx
Labels: kind/fix

#536 refactor: added typings for root state
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/rootReducer.ts
  webapp/src/app/rootStore.ts
  webapp/src/app/rootTypes.ts
  webapp/src/containers/BlockchainPage/reducer.ts
  webapp/src/containers/BlockchainPage/types.ts
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/ConsolePage/reducer.ts
  webapp/src/containers/ConsolePage/types.ts
  webapp/src/containers/LiquidityPage/reducer.ts
  webapp/src/containers/LiquidityPage/types.ts
  webapp/src/containers/MasternodesPage/reducer.ts
  webapp/src/containers/MasternodesPage/types.ts
  webapp/src/containers/PopOver/reducer.ts
  webapp/src/containers/PopOver/types.ts
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/types.ts
  webapp/src/containers/SettingsPage/__test__/__snapshots__/settingsHeader.test.tsx.snap
  webapp/src/containers/SettingsPage/components/SettingsChangePassphrase/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/reducer.ts
  webapp/src/containers/SettingsPage/types.ts
  webapp/src/containers/SwapPage/reducer.ts
  webapp/src/containers/SwapPage/types.ts
  webapp/src/containers/SyncStatus/reducer.ts
  webapp/src/containers/SyncStatus/types.ts
  webapp/src/containers/TokensPage/reducer.ts
  webapp/src/containers/TokensPage/types.ts
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateOrRestoreWalletPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateWallet.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/WalletTxnsNew.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/reducer.ts
  webapp/src/containers/WalletPage/saga.tsx
  webapp/src/containers/WalletPage/types.ts
  webapp/src/utils/rpc-client.ts
Labels: kind/refactor

#540 issue needs/triage comment updated to include community channels
  .github/governance.yml
Labels: kind/chore

#552 chore: disable opening of browser on build
  webapp/webpack/config/devServer.js
Labels: kind/chore
