Repository DeFiCh/defichain-app, pull requests merged in 2021-12, with the labels that each got.

#1066 moved snapshot folder into ~/.defi/
  electron-app/src/utils.ts
Labels: kind/fix

#1080 `liquidity page updates`
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/assets/svg/dAAPL.svg
  webapp/src/assets/svg/dAMD.svg
  webapp/src/assets/svg/dAMZN.svg
  webapp/src/assets/svg/dARKK.svg
  webapp/src/assets/svg/dBABA.svg
  webapp/src/assets/svg/dCOIN.svg
  webapp/src/assets/svg/dFB.svg
  webapp/src/assets/svg/dGLD.svg
  webapp/src/assets/svg/dGME.svg
  webapp/src/assets/svg/dGOOGL.svg
  webapp/src/assets/svg/dMSFT.svg
  webapp/src/assets/svg/dNVDA.svg
  webapp/src/assets/svg/dPDBC.svg
  webapp/src/assets/svg/dPLTR.svg
  webapp/src/assets/svg/dQQQ.svg
  webapp/src/assets/svg/dSLV.svg
  webapp/src/assets/svg/dSPY.svg
  webapp/src/assets/svg/dTLT.svg
  webapp/src/assets/svg/dTSLA.svg
  webapp/src/assets/svg/dTWTR.svg
  webapp/src/assets/svg/dURTH.svg
  webapp/src/assets/svg/dUSD.svg
  webapp/src/assets/svg/dVNQ.svg
  webapp/src/components/LiquidityAccordion/index.tsx
  webapp/src/components/PairIcon/index.tsx
  webapp/src/constants/configs.ts
  webapp/src/containers/LiquidityPage/__test__/availablePoolPairsList.test.tsx
  webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx
  webapp/src/containers/LiquidityPage/components/AvailablePoolPairsList/index.tsx
  webapp/src/containers/LiquidityPage/components/LiquidityInfo/index.tsx
  webapp/src/containers/LiquidityPage/index.tsx
  webapp/src/containers/LiquidityPage/saga.tsx
  webapp/src/containers/LiquidityPage/service.tsx
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/types.ts
  webapp/src/containers/SyncStatus/service.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/utils/utility.ts
Labels: kind/feature

#1108 Add composite swap, update to 2.3.2, refactor scripts, node terminology and more
  .gitignore
  README.md
  electron-app/src/app.ts
  electron-app/src/constants/app.ts
  electron-app/src/constants/dirpath.ts
  electron-app/src/menus/index.ts
  electron-app/src/services/defiprocessmanager.ts
  package-lock.json
  package.json
  pre-build-linux.sh
  pre-build-mac.sh
  pre-build-win.cmd
  scripts/electron.js
  scripts/prebuild.js
  typings/ipcEvents.ts
  typings/rpcMethods.ts
  typings/settings.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/__test__/service.test.tsx
  webapp/src/app/service.tsx
  webapp/src/app/snapshot.ipcRenderer.ts
  webapp/src/app/update.ipcRenderer.ts
  webapp/src/containers/ConsolePage/ConsoleComponent/console.scss
  webapp/src/containers/MasternodesPage/__test__/saga.test.tsx
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/PopOver/SnapshotDownloadModal/index.tsx
  webapp/src/containers/PopOver/saga.tsx
  webapp/src/containers/RpcConfiguration/__test__/saga.test.ts
  webapp/src/containers/RpcConfiguration/saga.ts
  webapp/src/containers/SettingsPage/__test__/saga.test.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/containers/SettingsPage/service.tsx
  webapp/src/containers/SwapPage/index.tsx
  webapp/src/containers/WalletPage/saga.tsx
  webapp/src/utils/rpc-client.ts
  webapp/src/worker/queue/index.ts
  win-pre-build-scripts.ps1
Labels: kind/refactor

#1111 update default branch to `main`
  .github/workflows/dev-builds.yml
  .github/workflows/oss-governance-bot.yml
  .github/workflows/release-builds.yml
  .github/workflows/release-drafter.yml
  .github/workflows/sync-labels.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/prebuild.js
  webapp/package-lock.json
  webapp/package.json
Labels: kind/chore
