Repository DeFiCh/defichain-app, pull requests merged in 2021-03, with the labels that each got.

#566 fix: wait for binary to close before updating
  webapp/src/app/update.ipcRenderer.ts
Labels: kind/fix

#580 feat: updated german translations
  webapp/src/translations/languages/de.json
Labels: kind/feature

#567 fix: improve reindex issue occurence
  electron-app/src/services/defiprocessmanager.ts
Labels: kind/fix

#558 fix: wallet map issues
  electron-app/src/app.ts
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
Labels: kind/fix

#579 feature/csv export
  webapp/src/containers/WalletPage/components/WalletTxnsNew/CsvRowInput/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/WalletTxns.module.scss
  webapp/src/containers/WalletPage/components/WalletTxnsNew/components/DownloadCsvModal/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/components/csvRowToggle/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/feature

#507 Masternode new ux
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  electron-app/src/services/uiconfig.ts
  electron-app/src/utils.ts
  package.json
  typings/settings.ts
  webapp/.eslintrc.js
  webapp/src/constants/configs.ts
  webapp/src/constants/units.ts
  webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/MasterNodeTabHeader.module.scss
  webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx
  webapp/src/containers/MasternodesPage/components/MasterNodesList/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/MineNodeList.module.scss
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
  webapp/src/containers/MasternodesPage/index.tsx
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/PopOver/service.tsx
  webapp/src/containers/SettingsPage/index.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/containers/Sidebar/Sidebar.module.scss
  webapp/src/containers/Sidebar/index.tsx
  webapp/src/containers/TokensPage/saga.tsx
  webapp/src/routes/index.tsx
  webapp/src/scss/_layout.scss
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
  webapp/src/utils/passwordUtility.ts
Labels: kind/feature

#581 fix: remap unable to sign err message
  webapp/src/constants/common.ts
Labels: kind/fix

#587 Fix masternode ui
  webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
Labels: kind/fix

#583 Fix/wallet UI
  webapp/src/components/KeyValueLi/ValueLi/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Labels: kind/fix

#585 chore: bump app 2.3.1 and node to 1.5.1
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/chore

#590 Fix: Change footer to white
  webapp/src/scss/_layout.scss
Labels: kind/fix

#584 fix: unlock wallet if masternode is present
  electron-app/src/app.ts
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  electron-app/src/services/uiconfig.ts
  electron-app/src/utils.ts
  typings/rpcConfig.ts
  webapp/src/app/App.tsx
  webapp/src/containers/MasternodesPage/__test__/MasterNodesList.test.tsx
  webapp/src/containers/MasternodesPage/__test__/MasternodeTab.test.tsx
  webapp/src/containers/MasternodesPage/__test__/StatisticsTab.test.tsx
  webapp/src/containers/MasternodesPage/__test__/index.test.tsx
  webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx
  webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx
  webapp/src/containers/MasternodesPage/components/MasterNodesList/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
  webapp/src/containers/MasternodesPage/index.tsx
  webapp/src/containers/MasternodesPage/reducer.ts
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/MasternodesPage/service.tsx
  webapp/src/containers/MasternodesPage/types.ts
  webapp/src/containers/PopOver/MasternodeWarningModal/index.tsx
  webapp/src/containers/PopOver/UpdateProgress/ErrorComponent.tsx
  webapp/src/containers/PopOver/UpdateProgress/ShowUpdateAvailable.tsx
  webapp/src/containers/PopOver/reducer.ts
  webapp/src/containers/PopOver/types.ts
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/saga.ts
  webapp/src/containers/RpcConfiguration/types.ts
  webapp/src/containers/SettingsPage/components/SettingsRowDropDown/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/containers/SettingsPage/types.ts
  webapp/src/containers/Sidebar/index.tsx
  webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx
  webapp/src/containers/WalletPage/components/WalletPassphrasePage/walletPassphrasePage.module.scss
  webapp/src/scss/_layout.scss
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/utils/rpc-client.ts
  webapp/src/utils/utility.ts
Labels: kind/fix

#592 feat: community wiki on help page
  webapp/src/constants/configs.ts
  webapp/src/containers/HelpPage/index.tsx
  webapp/src/translations/languages/en.json
Labels: kind/feature

#593 fix: add label on auto-lock disable
  webapp/src/containers/HelpPage/HelpPage.module.scss
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/settingsTabSecurity.module.scss
  webapp/src/translations/languages/en.json
Labels: kind/fix

#594 fix: updated labels
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/fix

#595 Update 20k to 20,000
  webapp/src/translations/languages/en.json
Labels: kind/feature

#600 feat: call spv_resync on start
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  electron-app/src/utils.ts
  typings/walletMap.ts
  webapp/src/app/service.tsx
Labels: kind/feature

#601 fix CSV-UI
  webapp/src/constants/configs.ts
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Labels: kind/fix

#598 fix footer backdrop
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/scss/_layout.scss
Labels: kind/fix

#603 Add BCH icon
  webapp/src/utils/utility.ts
Labels: kind/feature

#612 Fix/csv UI
  webapp/src/constants/configs.ts
Labels: kind/fix

#613 feat: enable/disable masternode
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
  typings/ipcEvents.ts
  typings/rpcConfig.ts
  webapp/src/app/App.scss
  webapp/src/app/App.tsx
  webapp/src/app/service.tsx
  webapp/src/containers/MasternodesPage/__test__/saga.test.tsx
  webapp/src/containers/MasternodesPage/__test__/service.test.tsx
  webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
  webapp/src/containers/MasternodesPage/index.tsx
  webapp/src/containers/MasternodesPage/masterNodeInterface.ts
  webapp/src/containers/MasternodesPage/reducer.ts
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/MasternodesPage/service.tsx
  webapp/src/containers/PopOver/MasternodeUpdateRestartModal/index.tsx
  webapp/src/containers/PopOver/reducer.ts
  webapp/src/containers/PopOver/types.ts
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/saga.ts
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/Sidebar/index.tsx
  webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/feature

#618 chore: bump node version to 1.5.2
  package.json
Labels: kind/feature

#622 fix: translations added and length update
  webapp/src/containers/MasternodesPage/components/MineNodeFooter/index.tsx
  webapp/src/translations/languages/de.json
Labels: kind/fix

#625 chore: update translations
  webapp/src/translations/languages/de.json
Labels: kind/chore

#627 fix: masternode settings update, BCH icon, remove liquidity arrow
  webapp/src/constants/configs.ts
  webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
  webapp/src/translations/languages/en.json
  webapp/src/utils/isElectron.ts
  webapp/src/utils/utility.ts
Labels: kind/fix

#617 refactor: removed dead codes and updated snap
  electron-app/src/services/defiprocessmanager.ts
  webapp/src/app/App.tsx
  webapp/src/app/__test__/testData.json
  webapp/src/components/KeyValueLi/ValueLi/index.tsx
  webapp/src/components/KeyValueLi/__test__/__snapshots__/ValueLi.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/service.test.tsx
  webapp/src/containers/HelpPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasterNodesList.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasternodeTab.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/StatisticsTab.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/MasternodesPage/components/MineNodeList/index.tsx
  webapp/src/containers/MasternodesPage/saga.tsx
  webapp/src/containers/PopOver/__test__/__snapshots__/BackupWalletWarningModel.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/EncryptWalletModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ErrorComponent.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/GeneralReIndexModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ReIndexModel.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/RefreshUtxosModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ResetWalletDatModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/RestartWalletModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ShowUpdateAvailable.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/WalletPassphraseModal.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/RpcConfiguration/types.ts
  webapp/src/containers/SettingsPage/__test__/__snapshots__/settingsTab.test.tsx.snap
  webapp/src/containers/SettingsPage/__test__/__snapshots__/settingsTabDisplay.test.tsx.snap
  webapp/src/containers/SettingsPage/__test__/saga.test.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/TokensPage/saga.tsx
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateOrRestoreWalletPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/WalletTxnsNew.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/walletTxn.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/walletTxn.test.tsx
  webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxns/WalletTxns.module.scss
  webapp/src/containers/WalletPage/components/WalletTxns/index.tsx
  webapp/src/containers/WalletPage/saga.tsx
  webapp/src/utils/__tests__/utility.test.ts
  webapp/src/utils/rpc-client.ts
  webapp/src/utils/utility.ts
  webapp/src/utils/validation.ts
  webapp/test/setupRpcInitialData.ts
Labels: kind/refactor

#403 Wallet drop
  webapp/src/components/TokenCard/TokenCard.module.scss
  webapp/src/components/TokenCard/WalletTokenCard/index.tsx
  webapp/src/components/walletDropdown/WalletDropdown.module.scss
  webapp/src/components/walletDropdown/index.tsx
  webapp/src/constants/configs.ts
  webapp/src/containers/Sidebar/index.tsx
  webapp/src/containers/WalletPage/WalletPage.module.scss
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx
  webapp/src/containers/WalletPage/index.tsx
  webapp/src/containers/WalletPage/service.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
  webapp/src/utils/utility.ts
Labels: kind/feature

#604 Fix/filter over screen
  webapp/src/containers/SettingsPage/components/SettingsChangePassphrase/index.tsx
  webapp/src/containers/WalletPage/components/CreateOrRestoreWalletPage/index.tsx
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/scss/_layout.scss
Labels: kind/fix

#615 Add check for launchAtLogin prevState
  webapp/src/containers/SettingsPage/__test__/saga.test.tsx
  webapp/src/containers/SettingsPage/saga.tsx
Labels: kind/fix

#634 Change 1 Million to 20,000
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
Labels: kind/fix

#642 fix: default path for wallet, bump app version to v2.3.2
  electron-app/src/services/dialogmanager.ts
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/walletDropdown/WalletDropdown.module.scss
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
Labels: kind/fix

#643 feat: added warning file on installation folder
  DO_NOT_SAVE_WALLETS_HERE/DO_NOT_SAVE_WALLETS_HERE.txt
  package.json
  webapp/src/containers/PopOver/UpdateProgress/PostUpdateComponent.tsx
Labels: kind/feature

#637 upgraded oss-governance-bot to v2
  .github/CODEOWNERS
  .github/governance.yml
  .github/workflows/oss-governance-bot.yml
Labels: kind/chore

#645 feat: select custom installation directory for Windows
  package.json
Labels: kind/feature

#654 chore: bump web dependencies and typescript
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
Labels: kind/chore

#652 fix: create directory if user accidentally deletes it
  electron-app/src/controllers/wallets.ts
Labels: kind/fix

#651 Switch from mnemonic phrase to Wallet Backup
  webapp/src/translations/languages/en.json
Labels: kind/docs

#658 feat: update app name to "DeFi"
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/governance.yml
  .github/workflows/dev-builds.yml
  .github/workflows/release-builds.yml
  DO_NOT_SAVE_WALLETS_HERE/DO_NOT_SAVE_WALLETS_HERE.txt
  README.md
  electron-app/src/ipc-events/appUpdateManager.ts
  electron-app/src/menus/index.ts
  electron-app/src/utils.ts
  package-lock.json
  package.json
  typings/settings.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/constants/settings.ts
  webapp/src/containers/BlockchainPage/__test__/__snapshots__/blockPage.test.tsx.snap
  webapp/src/containers/BlockchainPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ExchangePage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/HelpPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/addLiquidity.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/liquidityInfo.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/removeLiquidity.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasterNodesList.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasternodeTab.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/StatisticsTab.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/PostUpdateComponent.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ShowUpdateAvailable.test.tsx.snap
  webapp/src/containers/SwapPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/TokensPage/components/CreateToken/DCTDistribution/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateOrRestoreWalletPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateWallet.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/RestoreWallet.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/SendPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/createNewAddressPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/receive.test.tsx.snap
  webapp/src/containers/WalletPage/components/ReceivePage/CreateNewAddressPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/index.html
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/nl.json
  webapp/src/utils/__tests__/utility.test.ts
Labels: kind/feature

#659 chore: update german translations
  webapp/src/translations/languages/de.json
Labels: kind/fix

#661 Fix/csv UI
  webapp/src/constants/configs.ts
  webapp/src/containers/RpcConfiguration/reducer.ts
  webapp/src/containers/WalletPage/components/WalletTxnsNew/components/DownloadCsvModal/index.tsx
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
Labels: kind/fix

#638 fix: update design of settings page
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/SettingsTabHeader.module.scss
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx
Labels: kind/fix

#663 fix: config issue
  electron-app/src/services/uiconfig.ts
  electron-app/src/utils.ts
Labels: kind/fix

#664 feat: updated app name to "DeFi Wallet"
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
  .github/governance.yml
  .github/workflows/dev-builds.yml
  .github/workflows/release-builds.yml
  DO_NOT_SAVE_WALLETS_HERE/DO_NOT_SAVE_WALLETS_HERE.txt
  README.md
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/components/TokenCard/__test__/__snapshots__/WalletTokenCard.test.tsx.snap
  webapp/src/constants/settings.ts
  webapp/src/containers/BlockchainPage/__test__/__snapshots__/blockPage.test.tsx.snap
  webapp/src/containers/BlockchainPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ExchangePage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/HelpPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/addLiquidity.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/liquidityInfo.test.tsx.snap
  webapp/src/containers/LiquidityPage/__test__/__snapshots__/removeLiquidity.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasterNodesList.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/MasternodeTab.test.tsx.snap
  webapp/src/containers/MasternodesPage/__test__/__snapshots__/StatisticsTab.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/PostUpdateComponent.test.tsx.snap
  webapp/src/containers/PopOver/__test__/__snapshots__/ShowUpdateAvailable.test.tsx.snap
  webapp/src/containers/SwapPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/TokensPage/components/CreateToken/CreateDCT/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/TokensPage/components/CreateToken/DCTDistribution/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateOrRestoreWalletPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/CreateWallet.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/RestoreWallet.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/SendPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/WalletTxnsNew.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/createNewAddressPage.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/__test__/__snapshots__/receive.test.tsx.snap
  webapp/src/containers/WalletPage/components/ReceivePage/CreateNewAddressPage/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/index.html
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/nl.json
  webapp/src/utils/__tests__/utility.test.ts
Labels: kind/feature

#665 fix: restore wallet issue
  electron-app/src/controllers/wallets.ts
Labels: kind/fix

#667 fix: release asset updates
  .github/workflows/release-builds.yml
Labels: kind/chore

#668 chore: update translation
  webapp/src/translations/languages/de.json
Labels: kind/fix

#672 fix: ui updates
  webapp/src/containers/HelpPage/index.tsx
  webapp/src/containers/PopOver/BackupWalletWarningModel/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/SettingsTabHeader.module.scss
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx
  webapp/src/scss/_layout.scss
  webapp/src/translations/languages/en.json
Labels: kind/fix

#679 Fix/UI
  webapp/src/constants/configs.ts
  webapp/src/containers/MasternodesPage/components/MineNodeList/components/MineNodeCard/index.tsx
  webapp/src/containers/PopOver/MasternodeUpdateRestartModal/index.tsx
Labels: kind/fix

#675 Fix/settings page ui
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
Labels: kind/fix

#674 Fix/token search bar
  webapp/src/containers/TokensPage/__test__/__snapshots__/tokenList.test.tsx.snap
  webapp/src/containers/TokensPage/__test__/tokenList.test.tsx
  webapp/src/containers/TokensPage/components/TokenList/index.tsx
  webapp/src/containers/TokensPage/index.tsx
  webapp/src/containers/TokensPage/reducer.ts
  webapp/src/containers/TokensPage/saga.tsx
  webapp/src/containers/TokensPage/service.tsx
  webapp/src/utils/utility.ts
Labels: kind/fix

#683 chore: bump node version to 1.6.0
  package.json
Labels: kind/fix

#684 feat: display node version on CLI
  package.json
  webapp/package.json
  webapp/src/constants/settings.ts
  webapp/src/containers/ConsolePage/ConsoleComponent/index.tsx
Labels: kind/feature

#692 fix: load address on import
  typings/rpcConfig.ts
  typings/walletMap.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/service.tsx
  webapp/src/components/AddressDropdown/index.tsx
  webapp/src/containers/LiquidityPage/__test__/service.test.tsx
  webapp/src/containers/LiquidityPage/components/AddLiquidity/index.tsx
  webapp/src/containers/LiquidityPage/components/RemoveLiquidity/index.tsx
  webapp/src/containers/LiquidityPage/service.tsx
  webapp/src/containers/PopOver/RestoreWalletModal/index.tsx
  webapp/src/containers/SettingsPage/service.tsx
  webapp/src/containers/SwapPage/__test__/service.test.tsx
  webapp/src/containers/SwapPage/index.tsx
  webapp/src/containers/SwapPage/service.tsx
  webapp/src/containers/TokensPage/components/CreateToken/index.tsx
  webapp/src/containers/TokensPage/service.tsx
  webapp/src/containers/WalletPage/__test__/reducers.test.tsx
  webapp/src/containers/WalletPage/__test__/saga.test.tsx
  webapp/src/containers/WalletPage/__test__/services.test.tsx
  webapp/src/containers/WalletPage/__test__/testData.json
  webapp/src/containers/WalletPage/components/ReceivePage/CreateNewAddressPage/index.tsx
  webapp/src/containers/WalletPage/components/ReceivePage/PaymentRequestList/index.tsx
  webapp/src/containers/WalletPage/reducer.ts
  webapp/src/containers/WalletPage/saga.tsx
  webapp/src/containers/WalletPage/service.tsx
  webapp/src/containers/WalletPage/types.ts
  webapp/src/utils/rpc-client.ts
  webapp/src/utils/utility.ts
Labels: kind/fix

#693 fix: remove node validation and fix for exit wallet
  electron-app/src/controllers/wallets.ts
  electron-app/src/services/defiprocessmanager.ts
Labels: kind/fix

#696 Fix/Send page max amount logic
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
Labels: kind/fix

#660 Feature/hide consolidate utxos
  webapp/src/containers/MasternodesPage/components/MasterNodeDetailPage/index.tsx
  webapp/src/containers/MasternodesPage/index.tsx
  webapp/src/containers/SettingsPage/__test__/SettingsTabGeneral.test.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabGeneral/SettingTabGeneral.module.scss
  webapp/src/containers/SettingsPage/components/SettingsTabGeneral/index.tsx
  webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx
  webapp/src/containers/SettingsPage/index.tsx
  webapp/src/containers/SettingsPage/saga.tsx
  webapp/src/containers/SettingsPage/service.tsx
  webapp/src/containers/TokensPage/components/CreateToken/index.tsx
  webapp/src/containers/TokensPage/components/MintToken/index.tsx
  webapp/src/containers/TokensPage/components/TokenInfo/index.tsx
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
  webapp/src/utils/utility.ts
Labels: kind/feature

#697 Fix/cursor jumps before & after {}
  webapp/src/containers/ConsolePage/ConsoleComponent/console.scss
Labels: kind/fix

#715 Added block reward in transaction
  webapp/src/containers/WalletPage/components/WalletTxnsNew/index.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/fr.json
  webapp/src/translations/languages/nl.json
  webapp/src/translations/languages/ru.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/fix
