Repository DeFiCh/defichain-app, pull requests merged in 2021-08, with the labels that each got.

#1020 Set 6 Tokens per page to avoid having an empty space
  webapp/src/constants/configs.ts
Labels: kind/chore

#1022 address validation and bump package
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/TransactionsPage/components/SendPage/index.tsx
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/utils/utility.ts
Labels: kind/feature

#1034 Improve English language file
  webapp/src/translations/languages/en.json
Labels: kind/chore, version/2.6.3
