Repository DeFiCh/defichain-app, pull requests merged in 2021-05, with the labels that each got.

#792 feat: add defichain analytics site to DEX
  webapp/src/constants/configs.ts
  webapp/src/containers/SwapPage/index.tsx
  webapp/src/containers/SwapPage/swap.module.scss
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/feature

#787 chore: update chinese translations
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/chore

#814 fix: labels, defichain.com links
  typings/settings.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/SettingsPage/components/SettingsTabSecurity/index.tsx
  webapp/src/containers/SettingsPage/types.ts
  webapp/src/containers/WalletPage/components/WalletPassphrasePage/index.tsx
Labels: kind/fix

#815 feat: update snapshot
  typings/snapshot.ts
Labels: kind/feature

#824 chore: update snapshot 835791
  typings/snapshot.ts
Labels: kind/chore

#826 chore: bump to 838093 and update app version to 2.3.4
  package-lock.json
  package.json
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/containers/PopOver/UpdateProgress/ErrorComponent.tsx
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/translations/languages/de.json
Labels: kind/chore

#828 feat: add api for fees, disabled spv
  electron-app/src/services/defiprocessmanager.ts
  webapp/src/constants/configs.ts
  webapp/src/containers/WalletPage/components/Balances/index.tsx
  webapp/src/containers/WalletPage/components/SendPage/index.tsx
  webapp/src/containers/WalletPage/spvService.tsx
  webapp/src/utils/rpc-client.ts
  webapp/src/worker/schedular/updateBalance.ts
Labels: kind/feature

#836 feat: add SPV Wallet
  electron-app/src/services/defiprocessmanager.ts
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/components/Balances/index.tsx
  webapp/src/worker/schedular/updateBalance.ts
Labels: kind/feature

#845 Update 2-enhancement.md
  .github/ISSUE_TEMPLATE/2-enhancement.md
Labels: kind/chore

#844 Update 1-bug-report.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
Labels: kind/chore

#847 chore: bump packages
  electron-app/src/services/defiprocessmanager.ts
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/WalletPage/components/Balances/index.tsx
  webapp/src/worker/schedular/updateBalance.ts
Labels: kind/chore

#842 fix: mac issues on initial install
  electron-app/src/utils.ts
  typings/snapshot.ts
Labels: kind/fix

#850 feat: display UTXO and Token DFI
  webapp/src/containers/WalletPage/components/Balances/Balances.module.scss
  webapp/src/containers/WalletPage/components/Balances/BalancesTokenCard/index.tsx
  webapp/src/containers/WalletPage/components/Balances/index.tsx
  webapp/src/containers/WalletPage/reducer.ts
  webapp/src/containers/WalletPage/service.tsx
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
Labels: kind/feature

#851 fix: decrease interval of polling, shutdown
  electron-app/src/app.ts
  electron-app/src/constants/app.ts
Labels: kind/fix

#863 feat: bump node to 1.7.0
  electron-app/src/controllers/snapshot.ts
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/constants/configs.ts
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/HelpPage/index.tsx
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/feature

#880 feat: update index file
  electron-app/src/controllers/snapshot.ts
Labels: kind/feature

#884 chore: bump to 2.4.0-rc.4 and node 1.7.2
  electron-app/src/controllers/snapshot.ts
  package-lock.json
  package.json
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/chore

#885 chore: bump app to 2.4.0 and updated snapshot index
  package-lock.json
  package.json
  typings/snapshot.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/LaunchScreen/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/containers/ConsolePage/__test__/__snapshots__/consoleComponent.test.tsx.snap
  webapp/src/containers/Sidebar/__test__/__snapshots__/index.test.tsx.snap
  webapp/src/translations/languages/de.json
  webapp/src/translations/languages/en.json
  webapp/src/translations/languages/zhs.json
  webapp/src/translations/languages/zht.json
Labels: kind/chore
